# Generated by Django 5.2.1 on 2025-07-10 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_certificate'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeServices',
            fields=[
                ('pk_type_services', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fk_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_services', to='management.management')),
            ],
        ),
    ]
