# Generated by Django 5.2.1 on 2025-07-10 17:01

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('core', '0001_initial'),
        ('management', '0003_collectorusers'),
        ('services', '0001_initial'),
        ('waste', '0002_wastesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeServices',
            fields=[
                ('pk_type_services', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fk_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_services', to='management.management')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('pk_services', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Servicio')),
                ('service_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Servicio')),
                ('scheduled_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 10))], verbose_name='Fecha Programada')),
                ('fk_clients', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Cliente')),
                ('fk_locations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location', verbose_name='Ubicación')),
                ('fk_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.status', verbose_name='Estado')),
                ('fk_waste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waste.waste', verbose_name='Residuo')),
                ('fk_waste_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waste.wastesubcategory', verbose_name='Subcategoría de Residuo')),
                ('fk_type_services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.typeservices', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
