# Generated by Django 5.2.1 on 2025-07-30 03:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_typeservices_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='scheduled_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 29))], verbose_name='Fecha Programada'),
        ),
    ]
