# Generated by Django 5.2.1 on 2025-07-30 05:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_scheduled_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('pk_service_log', models.AutoField(primary_key=True, serialize=False)),
                ('completed_date', models.DateTimeField()),
                ('waste_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('document', models.FileField(blank=True, null=True, upload_to='service_logs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('fk_services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.services')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Log',
                'verbose_name_plural': 'Service Logs',
                'db_table': 'ServiceLog',
            },
        ),
    ]
