# Generated by Django 5.2.1 on 2025-08-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_certificate'),
        ('services', '0005_alter_services_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='fk_management',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='management.management', verbose_name='Management'),
            preserve_default=False,
        ),
    ]
