# Generated by Django 5.2.1 on 2025-08-02 15:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_fk_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='scheduled_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 2))], verbose_name='Fecha Programada'),
        ),
    ]
