# Generated by Django 5.2.1 on 2025-08-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_services_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservices',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
