# Generated by Django 5.2.1 on 2025-08-03 21:43

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_certificate'),
        ('services', '0008_alter_typeservices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='scheduled_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 3))], verbose_name='Fecha Programada'),
        ),
        migrations.AlterField(
            model_name='typeservices',
            name='fk_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_services', to='management.management'),
        ),
    ]
