# Generated by Django 5.2.1 on 2025-08-03 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_certificate'),
        ('core', '0002_alter_location_exterior_number_and_more'),
        ('management', '0004_delete_certificate'),
        ('services', '0009_alter_services_scheduled_date'),
        ('waste', '0003_wastesubcategory_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringService',
            fields=[
                ('pk_recurring_service', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Servicio Recurrente')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('custom', 'Personalizado')], max_length=10, verbose_name='Frecuencia')),
                ('custom_days', models.PositiveIntegerField(blank=True, help_text='Solo para frecuencia personalizada', null=True, verbose_name='Días personalizados')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin (opcional)')),
                ('next_generation_date', models.DateField(verbose_name='Próxima fecha de generación')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('cancelled', 'Cancelado')], default='active', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_services', to=settings.AUTH_USER_MODEL)),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_services', to='client.client', verbose_name='Cliente')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location', verbose_name='Ubicación')),
                ('fk_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_services', to='management.management', verbose_name='Management')),
                ('fk_type_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.typeservices', verbose_name='Tipo de Servicio')),
                ('fk_waste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waste.waste', verbose_name='Residuo')),
                ('fk_waste_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waste.wastesubcategory', verbose_name='Subcategoría de Residuo')),
            ],
            options={
                'verbose_name': 'Servicio Recurrente',
                'verbose_name_plural': 'Servicios Recurrentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceNotification',
            fields=[
                ('pk_notification', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_service', 'Nuevo Servicio'), ('service_approved', 'Servicio Aprobado'), ('service_rejected', 'Servicio Rechazado'), ('service_completed', 'Servicio Completado'), ('recurring_paused', 'Recurrencia Pausada'), ('recurring_cancelled', 'Recurrencia Cancelada')], max_length=20, verbose_name='Tipo de notificación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('fk_recurring_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.recurringservice', verbose_name='Servicio recurrente relacionado')),
                ('fk_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Servicio relacionado')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destinatario')),
            ],
            options={
                'verbose_name': 'Notificación de Servicio',
                'verbose_name_plural': 'Notificaciones de Servicios',
                'ordering': ['-created_at'],
            },
        ),
    ]
