# Generated by Django 5.2.1 on 2025-08-05 00:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_services_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='scheduled_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 4))], verbose_name='Fecha Programada'),
        ),
    ]
