# Generated by Django 5.2.1 on 2025-08-06 06:09

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_certificate'),
        ('services', '0010_alter_services_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='fk_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.collectorusers', verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='services',
            name='scheduled_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 5))], verbose_name='Fecha Programada'),
        ),
    ]
