# Generated by Django 5.2.1 on 2025-08-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_recurringservice_servicenotification'),
    ]

    operations = [
    ]
