# Generated by Django 5.2.1 on 2025-08-06 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_services_fk_collector_alter_services_scheduled_date'),
        ('waste', '0003_wastesubcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='fk_waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waste.waste', verbose_name='Residuo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='fk_waste_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waste.wastesubcategory', verbose_name='Subcategoría de Residuo'),
        ),
    ]
