# Generated by Django 5.2.1 on 2025-08-06 07:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_certificate'),
        ('services', '0012_services_fk_collector'),
        ('waste', '0003_wastesubcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='fk_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='management.management', verbose_name='Management'),
        ),
        migrations.AlterField(
            model_name='services',
            name='fk_waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waste.waste', verbose_name='Residuo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='fk_waste_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='waste.wastesubcategory', verbose_name='Subcategoría de Residuo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='scheduled_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 6))], verbose_name='Fecha Programada'),
        ),
    ]
