# Generated by Django 5.2.1 on 2025-07-07 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteSubCategory',
            fields=[
                ('pk_waste_subcategory', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste', to='waste.waste')),
            ],
        ),
    ]
