# Generated by Django 5.2.1 on 2025-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_wastesubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesubcategory',
            name='name',
            field=models.CharField(default=1, help_text='Nombre corto de la subcategoría', max_length=100),
            preserve_default=False,
        ),
    ]
