# Generated by Django 5.2.1 on 2025-07-06 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Managment',
            fields=[
                ('pk_managment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementWaste',
            fields=[
                ('pk_management_waste', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_managements', to='waste.waste')),
                ('fk_managment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_managements', to='managment.managment')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementUser',
            fields=[
                ('pk_managment_user', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_users', to=settings.AUTH_USER_MODEL)),
                ('fk_managment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='managment.managment')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementLocations',
            fields=[
                ('pk_management_locations', models.AutoField(primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.location')),
                ('fk_managment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_locations', to='managment.managment')),
            ],
        ),
    ]
