# Generated by Django 5.2.1 on 2025-07-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementlocations',
            name='fk_managment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_locations', to='management.managment'),
        ),
        migrations.AlterField(
            model_name='managementuser',
            name='fk_managment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='management.managment'),
        ),
        migrations.AlterField(
            model_name='managementwaste',
            name='fk_managment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_managements', to='management.managment'),
        ),
    ]
