# Generated by Django 5.2.1 on 2025-07-07 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('pk_certificate', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=255, unique=True)),
                ('pdf', models.FileField(unique=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='management.management')),
            ],
        ),
    ]
