# Generated by Django 5.2.1 on 2025-08-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_collectorusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
