# Generated by Django 5.2.1 on 2025-07-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('managment', 'Gerencia'), ('client', 'Cliente'), ('collector', 'Recolector')], default='managment', max_length=10, verbose_name='role'),
        ),
    ]
