# Generated by Django 5.2.1 on 2025-07-07 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('management', '0002_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pk_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('legal_name', models.CharField(max_length=255, unique=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.management')),
            ],
        ),
        migrations.CreateModel(
            name='ClientsLocations',
            fields=[
                ('pk_client_location', models.AutoField(primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=True)),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='ClientsUsers',
            fields=[
                ('pk_client_user', models.AutoField(primary_key=True, serialize=False)),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
